name: bactria
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - raxml-ng
  - macse
  - perl-bio-phylo-forest-dbtree
  - appdirs=1.4.4
  - attrs=22.2.0
  - biopython=1.81
  - cattrs=22.2.0
  - certifi=2022.12.7
  - charset-normalizer=3.1.0
  - click=8.1.3
  - ConfigArgParse=1.5.3
  - connection-pool=0.0.3
  - contourpy=1.0.7
  - cycler=0.11.0
  - datrie=0.8.2
  - DendroPy=4.5.2
  - docutils=0.19
  - dpath=2.1.5
  - et-xmlfile=1.1.0
  - fastjsonschema=2.16.3
  - fonttools=4.39.0
  - geojson-rewind=1.0.3
  - geomet=1.0.0
  - gitdb=4.0.10
  - GitPython=3.1.31
  - humanfriendly=10.0
  - idna=3.4
  - Jinja2=3.1.2
  - nbformat=5.8.0
  - jsonschema=4.17.3
  - jupyter_core=5.3.0
  - kiwisolver=1.4.4
  - MarkupSafe=2.1.2
  - matplotlib=3.7.1
  - muscle=0.0.4
  - nbformat=5.8.0
  - numpy=1.24.2
  - openpyxl=3.1.2
  - opentree=1.0.1
  - packaging=23.0
  - pandas=1.5.3
  - Pillow=9.4.0
  - plac=1.3.5
  - platformdirs=3.1.1
  - psutil=5.9.4
  - PuLP=2.7.0
  - pygbif=0.6.2
  - pyparsing=3.0.9
  - pyrsistent=0.19.3
  - python-dateutil=2.8.2
  - pytz=2022.7.1
  - PyYAML=6.0
  - requests=2.28.2
  - requests-cache=1.0.0
  - reretry=0.11.8
  - six=1.16.0
  - smart-open=6.3.0
  - smmap=5.0.0
  - snakemake=7.25.0
  - stopit=1.1.2
  - tabulate=0.9.0
  - throttler=1.2.2
  - toposort=1.10
  - traitlets=5.9.0
  - url-normalize=1.4.3
  - urllib3=1.26.15
  - wrapt=1.15.0
  - yte=1.5.1  
