
# Used for parallelization by snakemake
cpu_cores: 8

# Used for scatter/gather processing, corresponds with the number of families within the taxon defined in fasta_filter
nfamilies: 17

# Used for verbosity, see `logging` from stdlib
log_level: 'INFO'

# Either use COI-5P or matK_rbcL
marker: COI-5P

# Minimum length to include (this fits COI-5P)
minlength: 600

# Minimum number of sequences per alignment
minseq: 3

# Maximum number of sequences per alignment
maxseq: 5000

# Nucleotide alignments (NT) or aminoacid (AA) for MACSE alignment
datatype: NT

# Choose which records to use from the database for the pipeline. filter_name only takes one name, so does filter level.
# filter levels: class, order, family, genus, all (no filter)
fasta_filter:
  filter_level: order
  filter_name: Primates

name: phylogeny

dependencies:
  - pip:
      - -r requirements.txt

file_names:
  bold_tsv: resources/BOLD_Public.18-Dec-2023/BOLD_Public.18-Dec-2023.tsv
  open_tre: resources/opentree/opentree14.9_tree/labelled_supertree/labelled_supertree.tre
  hmm: resources/hmm/COI-5P.hmm
  fasta_dir: results/fasta/family

