
# Either use COI-5P or matK_rbcL
marker: COI-5P

# IMPORTANT: This depends on your own system. You can check your cpu cores in a ubuntu terminal using the command ls
cpu_cores: 8


name: phylogeny

dependencies:
  - pip:
      - -r requirements.txt

file_names:
  bold_zip: ../data/BOLD_Public.30-Dec-2022.tar.gz
  bold_tsv: ../data/mnt/bold_public/datapackages/recent-data/BOLD_Public.30-Dec-2022.tsv

