
# Used for parallelization by snakemake
cpu_cores: 8

# Used for verbosity, see `logging` from stdlib
log_level: 'DEBUG'

# Either use COI-5P or matK_rbcL
marker: matK_rbcL

# Minimum length to include (this fits COI-5P)
minlength: 600

# Minimum number of sequences per alignment
minseq: 3

# Maximum number of sequences per alignment
maxseq: 5000

# Nucleotide alignments (NT) or aminoacid (AA) for MACSE alignment
datatype: NT

name: phylogeny

dependencies:
  - pip:
      - -r requirements.txt

file_names:
  bold_zip: ../data/BOLD_Public.30-Dec-2022.tar.gz
  bold_tsv: ../data/mnt/bold_public/datapackages/recent-data/BOLD_Public.30-Dec-2022.tsv
  hmm: ../data/hmm/COI-5P.hmm
  fasta_dir: ../data/fasta/family

