name: bactria
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - raxml-ng
  - hmmer
  - sqlite
  - perl-bio-phylo-forest-dbtree
  - graphviz
  - pip
  - pip:
    - biopython
    - numpy~=1.24.2
    - pandas~=1.5.3
    - requests~=2.28.2
